### ISSUE TITLE
USER STORY: About section

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#10]
As a **user**, I can **learn about the people behind the business** so that **I can make up my mind if I would feel comfortable using their service**.

## Acceptance Criteria
1. A short section about the Tailor.
2. An image of the tailor.
3. A read more button that will link to the About page when clicked.

## Tasks
- [x] Write the about section 
- [x] Find an image of the tailor
- [x] Code the section with the link to the About page
