### ISSUE TITLE
USER STORY: Services section

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#11]
As a **business owner**, I can **display some of he services we provide on the homepage** so that **it gives the user an idea of the type of services we offer**.

## Acceptance Criteria
1. A Services section which displays 2 or 3 different types of services.
2. Icons or Images to give a bit of visual feedback.
3. A read more link that leads to the Services page.

## Tasks
- [x] Write the content
- [x] Find images for the section or link Fontawesome for the icons
- [x] Write the code and the link to the Services page

**Comment by MoniPar** [comment]
Not entirely happy with the layout on larger screens.  Might have to revisit later if time permits

**Comment by MoniPar** [comment]
Managed to make it look better just needed to offset on larger screens.
