### ISSUE TITLE
USER STORY: About Page

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#13]
As a **user**, I can **easily navigate to the About page** so that **I can find more information about the people behind the business and how they operate**.

## Acceptance Criteria
1. More information about the Master Tailor and his experience in the craft.
2. A section about the process of Bespoke Tailoring with images.
3. Another Call to Action with link to Appointment Form.

## Tasks
- [x] Write the content
- [x] Format the page
- [x] Add the images

**Comment by MoniPar** [comment]
AC2 Process of Bespoke tailoring will be added to Services Page
