### ISSUE TITLE
USER STORY: Registration

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#16]
As a **user**, I can **register an account** so that **I can make an appointment with the master tailor**.

## Acceptance Criteria
1. A new user iis directed to the registration form when they click the 'Schedule'  Appointment button.
2. The form has fields for username, password and a submit button.
3. Upon clicking the submit button, the user is redirected to the homepage.

## Tasks
- [x] Create the user app and add it to INSTALLED_APPS
- [x] Install Django Allauth and configure settings.py
- [x] Connect urls
- [x] Modify the signup template
- [x] Add conditional to 'Schedule Appointment' button for unregistered user to be directed to signup page.
