### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#17]
As a **user**, I can **use my username and password** so that **I can login to my user account**.

## Acceptance Criteria
1. Users are directed to the login form when they click on the 'Login' link in the navbar.
2. Users can also login through the link in the registration form upon clicking the 'Schedule Appointment' button.
3. Users are asked for their Username and password to login.
4. After login, users are directed back to the home page.

## Tasks
- [x] Connect up the 'sign in' URL template to the navbar link
- [x] Add conditionals to show logout link when user is logged in
- [x] Modify the  'sign in' template
