### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#19]
As a **user**, I can **view my profile** so that **access my details and information**.

## Acceptance Criteria
1. Newly registered users are automatically set up with a profile page upon registration.
2. They are directed to their profile page rather than their home page upon registration.
3. A logged user can click on the 'User' Profile link in the navbar to be directed to their Profile page.

## Tasks
- [x] Create the profile view
- [x] Create the profile template
- [x] Create the route
- [x] Link to navigation
- [x] Restrict route to logged in users
- [x] Create the Profile model
- [x] Register the Profile model
- [x] Automate profile creation upon registration

**Comment by MoniPar** [comment]
There was just too much in this user story.  It needed to be broken down into at least 2, but I forgot to extend it and now it's repeated.
