### ISSUE TITLE
USER STORY: Create the Django project and app

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#2]
As a **developer**, I can **create the Django project and app** so that **I can set up the database**.

## Acceptance Criteria
1. Successfully created the Django project directory.
2. Successfully created the Tailoring app.
3. The basic skeleton project is up and running.

## Tasks
- [x] Create the Django project
- [x] Create the Tailoring app
- [x] Add it to the list of INSTALLED_APPS
- [x] Migrate the changes to the database
