### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#20]
As a **user**, I can **login to my profile** so that **I can access my information and view my details**.

## Acceptance Criteria
1.  When returning user logs into their account a profile link appears in the navbar.
2.  When the profile link is clicked, the user will be directed to the profile page.
3.  Only the logged in user is able to view his/her profile page.

## Tasks
- [x] Create the basic profile function-based view
- [x] Create the basic profile template
- [x] Create the route
- [x] Link to navigation
- [x] Make sure route is restricted to logged in users only

**Comment by MoniPar** [comment]
Should research Class based views and try amend the views.py file

**Comment by MoniPar** [comment]
Changed to Class based views.
