### ISSUE TITLE
USER STORY: Automating Profile Creation

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#21]
As a **developer**, I can **automate user profile creation upon registration** so that **the admin doesn't have to do it manually every time a user is registered**.

## Acceptance Criteria
1. The Profile page is populated with more fields consisting of information the business owner needs.
2. This will include a phone number, the date when they need the job done for, the type of event and the type of outfit they are looking to get.
3. A newly registered user will be directed to their profile page where they can view their information after registration

## Tasks
- [x] Extend Django's user model by creating a Profile model
- [x] Register the Profile Model
- [x] Automate profile creation upon registration.

**Comment by MoniPar** [comment]
Had to override the Django allauth signup form in order to get user's first-name and last-name in the User table.  Email was made required so that business owner has another contact for the customers.
