### ISSUE TITLE
USER STORY: Update User Profile

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#23]
As a **user**, I can **update my profile information** so that **change my details when necessary**.

## Acceptance Criteria
1. The profile page is an editable form populated with the user's information.
2. It can only be accessed by the logged in user.
3. The user is able to update their information and submit the form via the Update button at the bottom.
4. Form is validated before saved and the user is alerted to required fields/invalid inputs.
5. User is directed back to the profile page after successful update, showing the updated information.

## Tasks
- [x] Create the ProfileUpdateForm
- [x] Add form to view
- [x] Update the profile template
- [x] Update the profile view

**Comment by MoniPar** [comment]
User's first-name, last-name, username and email cannot be updated by the user.  Only the phone and their event's information is.  After updating the profile information, user is directed back to home rather than back to the profile page.  A success message notifying the user that their profile has been updated is displayed on the home page.
