### ISSUE TITLE
USER STORY: Appointment Booking

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#25]
As a **business owner**, I can **login and view appointments scheduled by my customers** so that **I can contact them back for approval/dismissal**.

## Acceptance Criteria
1. Admin has the facility to view the Appointments table in the Admin page.
2. Appointment table will specify the appointment type, date and time, the date submitted, the state of approval and any comments left by the customer. 
3. Admin can approve or dismiss appointments set by the customer.

## Tasks
- [x] Create the Appointment Model
- [x] Register the model to the admin site
- [x] Add action to approve appointments
