### ISSUE TITLE
USER STORY: View Appointment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#26]
As a **user**, I can **login and view my appointments** so that **I can check if my appointments have been approved**.

## Acceptance Criteria
1. User can see their past and future appointments listed.
2. User can check if their future appointments have been approved.

## Tasks
- [x] Create the Appointment view code
- [x] Create the Appointment view template
- [x] Connect up the URLs

**Comment by MoniPar** [comment]
Need to add pagination for when there are more than 6 appointments on page - New issue opened see "Pagination on Appointments Page"
