### ISSUE TITLE
USER STORY: Create Appointment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#27]
As a **user**, I can **schedule an appointment with the master tailor** so that **I can avail of their services**.

## Acceptance Criteria
1. Logged in user can click on the Add Appointment button to book a new appointment.
2. Appointment form has the necessary fields to complete appointment schedule.
3. Form has information to guide the user on how to schedule an appointment.
4. Submit button directs user to the 'appointments' page which shows all scheduled appointments.

## Tasks
- [x] Create the Appointment view
- [x] Link up the urls
- [x] Create the Appointment form template
- [x] Override the form_valid method to add the current logged in user before form is submitted
- [x] Create a get_absolute_url method to return the path to the 'appointments'page.

**Comment by MoniPar** [comment]
Need to add the Process information on the About/Services Page and link it in the form.  New issue added - see "Process link"
