### ISSUE TITLE
USER STORY: Delete Appointment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#29]
As a **user**, I can **delete my upcoming appointment** so that **I can reschedule at a later date**.

## Acceptance Criteria
1. User can delete an appointment from the 'appointment-detail' page.
2. When user clicks on delete button, they are directed to a confirmation page with 'delete' and 'cancel' buttons.
3. If user clicks cancel, they are brought back to the 'appointment-detail' page of the current appointment.
4. If user clicks delete, the appointment is deleted and user is directed back to the 'appointments'page.

## Tasks
- [x] Create the Delete Appointment view code
- [x] Add the Delete Appointment button
- [x] Create the Alert Deletion Confirmation template
- [x] Connect the URLs
