### ISSUE TITLE
USER STORY: Create the Heroku app and postgreSQL database

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#3]
As a **developer**, I can **set the project to use an external database** so that **my project can be deployed successfully**.

## Acceptance Criteria
1. Successful creation of the Heroku app.
2. Successful creation of the new postgreSQL database instance.
3. The database is connected to the workspace and to Heroku.

## Tasks
- [x] Create the app on Heroku
- [x] Create the database instance on ElephantSQL
- [x] Create the env.py file and add to .gitignore
- [x] Modify settings.py to make Django aware of the env.py and hook up the database
- [x] Migrate the database structure to the newly connected ElephantSQL database
- [x] Add config vars to Heroku
