### ISSUE TITLE
USER STORY: Choices default

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#31]
As a **developer**, I can **add an empty default choice** so that **the user is alerted when trying to submit an appointment without selecting the type and time**.

## Acceptance Criteria
1. The Appointment form displays '------' on the Choices fields.
2. When user tries to submit the form without selecting an appropriate choice, they are alerted to fill in the required fields.
3. The form submits successfully when all required fields are filled in. 

## Tasks
- [x] Add an empty tuple in constants.py
- [x] Edit the default attribute in models.py
- [x] Test to see if form displays and submits without selecting an appropriate choice
