### ISSUE TITLE
USER STORY: Alert Messages

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#32]
As a **developer**, I can **add alert messages** so that **user is notified if their form has been submitted or an error has occurred**.

## Acceptance Criteria
1. When a user creates an appointment and submits an alert shows up on the top of the page saying "Your appointment has been created successfully!".
2. When a user updates an appointment and submits an alert shows up on the top of the page saying "Your appointment has been updated successfully!".
3. When a user deletes an appointment and confirms, an alert shows up on the top of the page saying "Your appointment has been deleted!"
4.  When an error occurs and form is not submitted, user is notified with an alert message at the top. 

## Tasks
- [x] Add success messages to form_valid methods in views.py
- [x] Add success message to delete method for the AppointmentDelete view
- [x] Add error messages to form_invalid methods for Appointment Create and Update views

**Comment by MoniPar** [comment]
Success messages working fine.  Need to add validation in forms before I can test if error messages are working - related issue "Date validation"
