### ISSUE TITLE
USER STORY: Cloudinary Setup

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#4]
As a **developer**, I can **set up and connect the project to Cloudinary** so that **I can upload images to a persistent file store**.

## Acceptance Criteria
1. Successful connection between the project and Cloudinary.
2. Successful connection between Cloudinary and Heroku.
3. Configuration of Media and static files.

## Tasks
- [x] Add Cloudinary API environment variable to env.py and Heroku
- [x] Set DISABLE_COLLECTSTATIC on Heroku
- [x] Add Cloudinary libraries to INSTALLED_APPS in settings.py
- [x] Set Cloudinary as storage for media and static files in settings.py
