### ISSUE TITLE
USER STORY: Test Code Validation

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#40]
As a **developer**, I can **use free resources like W3C validors and CI's Plint** so that **I can audit my HTML, CSS and Python code**.

## Acceptance Criteria
1. All templates are audited using W3C HTML Validator return no errors and minor/no warnings.
2. Styles.css is auted using W3C Jigsaw Validator return no errors and minor/no warnings.
3. All custom and modified .py files are audited using CI's Python Linter return no errors and minor/no warnings.

## Tasks
- [x] Validate all HTML, fix errors & warnings and document
- [x] Validate CSS, fix errors & warnings and document
- [x] Validate .py files, fix errors & warnings and document

**Comment by MoniPar** [comment]
I had already started testing before I remembered that I should have added the process to issues and my kanban board.  Although my sprint has a lot of 'Must Have's for prioritisation, this still helped me organise my time better for getting this Milestone done.
