### ISSUE TITLE
USER STORY: Lighthouse Testing

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#41]
As a **developer**, I can **use Lighthouse Testing** so that **I audit the website's performance, accessibility, best practices and SEO**.

## Acceptance Criteria
1. Lighthouse reports are high (green) for performance, best practices & SEO and 100% for Accessibility for all the following pages:
- Home
- About
- Services
- Registration
- Login
- Profile
- Logout
- Appointments List without Appointments
- Appointments List without Profile
- Appointments List
- Appointment Create
- Appointment Detail
- Appointment Update
- Appointment Delete

## Tasks
- [x] Run lighhouse on each of the above
- [x] Fix issues affecting low scores
- [x] Take screenshots and add to documentation

**Comment by MoniPar** [comment]
This issue was done before I wrote it, however I found it useful to double check that I had all of the pages audited with lighthouse.
