### ISSUE TITLE
USER STORY: Responsiveness Testing

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#42]
As a **developer**, I can **use Chrome Developer Tools** so that **I test the responsiveness of my website at different screen sizes**.

## Acceptance Criteria
1. All pages are responsive on screens larger than 320px and smaller than 2560px
2. Screenshots of responsive layouts are included in documentation.
3. Any issues are recorded in documentation.

## Tasks
- [x] Ask friends and family to test on their devices
- [x] Fix any responsiveness issues they encounter
- [x] Open project in DevTools
- [x] Check responsiveness on devices at different screen sizes
- [x] Fix any remaining issues
- [x] Get screen shots of various features at different screen sizes
- [x] Document in TESTING.md
