### ISSUE TITLE
USER STORY: Browser Compatibility

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#43]
As a **developer**, I can **open the website in different browsers** so that **I can check that it is compatible with them**.

## Acceptance Criteria
1. Website is compatible with Chrome (test on phone, tablet and laptop).
2. Website is compatible with Firefox (test on phone and laptop).
3. Website is compatible with Edge (test on laptop)
4. Website is compatible with Safari (test on phone and tablet)

## Tasks
- [x] Open website on the above mentioned browsers and devices
- [x] Record outcomes in a table in TESTING.md
- [x] Record issues for future fixes
