### ISSUE TITLE
USER STORY: Test User Stories

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#44]
As a **developer**, I can **manually test each user story** so that **I can make sure that they are met**.

## Acceptance Criteria
1. User stories are listed under UX - Scope in README.md in the following categories: Users, Registered Users, Business Owner..
2. Each user story is mapped to the GitHub Issues.
3. Testing for each user story is documented in tables in TESTING.md. 

## Tasks
- [x] Transfer User Stories to README and map them to project issues
- [x] Create tables in TESTING
- [x] Document the outcomes for each User Story test
