### ISSUE TITLE
USER STORY: Feature Testing

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#45]
As a **developer**, I can **do manual tests on every feature** so that **I can make sure it works**.

## Acceptance Criteria
1. TESTING.md displays a table with features, actions and effects.
2. All interactive elements are listed in this table and tested.
3. Outcomes are recorded in the effects column.

## Tasks
- [x] Create table in TESTING
- [x] List all features and tests performed
- [x] Record outcomes under Effects column
