### ISSUE TITLE
USER STORY: Other essential documentation

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#49]
As a **developer**, I can **further elaborate my documentation** so that **I fulfill all assessment criteria**.

## Acceptance Criteria
1. README features other sections on Technologies used, Deployment, Forking and Cloning, Code and Media Credits & Acknowledgements.
2. No grammar or spelling mistakes.

## Tasks
- [x] Read over and update sections
- [x] Make sure links work 
- [x] Fix grammar and spelling mistakes
