### ISSUE TITLE
USER STORY: Preparation and Deployment

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#5]
As a **developer**, I can **give Django some more specific instructions** so that **the project is deployed successfully**.

## Acceptance Criteria
1. Django knows where the templates are stored.
2. Django knows where the project is being hosted.
3. Successful first deployment.

## Tasks
- [x] Set up the templates directory in settings.py
- [x] Add the Heroku hos name into ALLOWED_HOSTS in settings.py
- [x] Create the media, static and templates directories
- [x] Create a Procfile
- [x] Deploy

**Comment by MoniPar** [comment]
This took longer than expected as settings had to be reconfigured before full deployment to Heroku was successful.  Bug recorded in README.md under the heading "First Deployment Bug".
