### ISSUE TITLE
USER STORY: Validation on Type field

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#50]
As a **developer**, I can **write validation for the type field** so that **users are only allowed to choose the type in the right order**.

## Acceptance Criteria
1. Users get a validation error if they choose an appointment type in the wrong order.
2. First appointment is always consultation, if user has already scheduled a consultation then they can only choose details & design, so on so forth.

## Tasks
- [ ] Create a function to get the user's appointments.
- [ ] Add conditionals to allow users to select specific types depending on what is in their appointment's list.
- [ ] Might need to research this further as not sure it will be possible with the way I have written the constants.
