### ISSUE TITLE
USER STORY: Homepage

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#6]
As a **business owner**, I would **like users visiting our site to land on the homepage** so that **they can learn about us and the services we provide**.

## Acceptance Criteria
1. Website URL will direct user to the Homepage
2. Homepage will have some basic information about the business

## Tasks
- [x] Create the home view code
- [x] Create the base template and extend the home view template
- [x] Connect up the urls.py file
