### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#7]
As a **user**, I can **see the website's logo and links at the top of the page** so that **I can easily navigate to other parts of the website**.

## Acceptance Criteria
1. Header with the Tailor's Thimble logo is displayed.
2. Links to Home, About, Services, Register and Login pages are displayed.
3. Hamburger button for mobile toggles navbar links.

## Tasks
- [x] Design the Logo for the website
- [x] Add a header with the Logo and Navigation
- [x] Use Bootstrap 4 to create the responsive navbar
- [x] List out the links to the other pages
