### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#8]
As a **user**, I can **see contact details, shop address and social links at the bottom of the website** so that **I can follow/contact the business owner and the website creator**.

## Acceptance Criteria
1. A footer is displayed at the bottom of the page.
2. Contact details, social links and shop address are clearly displayed.
3. Copyright date and link to the website creator's Linkedin page.
4. All social links open in a new tab.

## Tasks
- [x] Add footer to the base template
- [x] Use Bootstrap 4 to create a responsive footer
- [x] Add information and links to social media
