### ISSUE TITLE
USER STORY: Call to Action

### ISSUE THREAD

**Issue by MoniPar** [MoniPar/tailors_thimble#9]
As a **business owner**, I would **like the homepage to have a Call to Action** so that **users are encouraged to schedule an appointment early on**.

## Acceptance Criteria
1. A hero image that draws the eye to the Schedule an Appointment button.
2. Some text about the Bespoke Tailoring Experience.
3. A visible Schedule an Appointment button which will eventually link to the Booking form.

## Tasks
- [x] Find an appropriate Hero image
- [x] Write the text that overlays the image
- [x] Write responsive code for the above
